#!/bin/sh

################################################################################
################################################################################

. config/options $1

mkdir -p $ADDON_BUILD/$PKG_ADDON_ID/bin
  cp $BUILD/$PKG_NAME-$PKG_VERSION/deleter $ADDON_BUILD/$PKG_ADDON_ID/bin
