#!/bin/sh

################################################################################
################################################################################

. config/options $1

cd $BUILD/$PKG_NAME-$PKG_VERSION

CFLAGS=`echo $CFLAGS | sed -e "s|-O3||g"`
CFLAGS=`echo $CFLAGS | sed -e "s|-ffast-math||g"`
LDFLAGS=`echo $LDFLAGS | sed -e "s|-O3||g"`
LDFLAGS=`echo $LdFLAGS | sed -e "s|-ffast-math||g"`

make
