#!/bin/sh

. config/options $1

[ -d $BUILD/$PKG_NAME ] && rm -rf $BUILD/$PKG_NAME
mkdir -p $BUILD/$PKG_NAME
tar -xzf $SOURCES/$PKG_NAME/v$PKG_VERSION.tar.gz -C $BUILD/$PKG_NAME
mv $BUILD/$PKG_NAME/deleter-$PKG_VERSION/* $BUILD/$PKG_NAME
rm -rf $BUILD/$PKG_NAME/deleter-$PKG_VERSION

